# Application to expose
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: docker.arvancloud.ir/traefik/whoami
---
# Service to reach the application on the cluster
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: default
  labels:
    app: whoami
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: whoami
  selector:
    app: whoami
---
# HTTPRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: demo-route
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`whoami.myexample.io`) && PathPrefix(`/`)
    kind: Rule
    services:
      - name: whoami
        port: 80
    middlewares:
      - name: demo

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: demo
  namespace: default
spec:
  plugin:
    demo:
      headers:
        message: "Hello from Demo Plugin!"



